#' This is a ggplot function, which depends upon ggplot2 and ggpubr
#'
#' ggpolot function to plot the summaried result of BCA standard curve (2nd degree polynomial model) as generated by prest().
#'
#'
#' @param x a dataframe of atleast two columns named "Conc" and "A595".
#' @keywords BCAplot, prest
#' @export
# @examples
# BCAplot()

BCAplot <- function(x){
  ggplot(x, aes(x=Conc, y=A595_bc)) +
    geom_point() +
    geom_errorbar(aes(ymin=A595_bc-se, ymax=A595_bc+se),
                  width=.02) +
    geom_smooth(se=FALSE, method = "lm", formula= y ~ poly(x,2), n=1000, size=.4) +
    labs(y = "Normalized A595", x="Conc (mg/ml)") +
    ggtitle("BCA Standard Curve") +
    theme_pubr()
}
